global:
  scrape_interval: 15s
  evaluation_interval: 5s
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['myapi:6003']
  metrics_path: '/tam-metrics'
- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']
- job_name: 'cadvisor'
  static_configs:
  - targets: ['cadvisor:8098']
- job_name: 'redis-exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['redis-exporter:9121']


